### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by Descolada** [adash-ahk/adash.ahk#1]
Hey!
I took a glance at the workings of your library and wanted to share some thoughts about it.

1. The shorthand `_` is in my opinion ill-chosen. An underscore is very often used as a placeholder to discard variables, which means it will have a LOT of potential conflicts. Eg `for _, value in Map()`. You might want to stick with `A`, which is less used and is familiar to those who used BigA (or are there major differences between the two?).
2. You have a bug in [drop](https://github.com/adash-ahk/adash.ahk/blob/main/adash.ahk#L95C3-L95C15): `[] != []` because each time a new array is created and the pointers won't match. Thus `param_array == []` is never true. 
3. `Drop` and some other similar functions have an inefficient loop to drop the elements. Instead you can specify the `Length` argument in `ArrayObj.RemoveAt(Index, Length)`.
4. [isFunction](https://github.com/adash-ahk/adash.ahk/blob/main/adash.ahk#L841) will fail in some cases such as for closures:
```
MyFunc()
MyFunc() {
    a := "Hello"
    MsgBox(Type(MyClosure))
    MyClosure() => MsgBox(a)
}
```
`HasMethod` will return the correct result though.
You might also want to think whether you consider classes implementing `Call` a "function" or not:
```
Test(Type)
class Test {
    static Call(msg) => MsgBox(msg)
}
```
5. [isInteger](https://github.com/adash-ahk/adash.ahk/blob/main/adash.ahk#L847) will fail with integer strings - is this wanted?
6. You could make some functions more compact (and also execute faster) by using fat arrow syntax instead. Shouldn't impact readability much if
```
	static isObject(param) {
		if (isObject(param)) {
			return true
		}
		return false
	}
```
is replaced by
```
	static isObject(param) => isObject(param)
```
7. I'm a bit confused about the objective of accepting strings as input but returning arrays as output. For example `drop` will turn a string into a character array and then return an array after dropping n characters. Wouldn't it make more sense to return an array in such cases?
8. The function of `static _guarded` eludes me, but my gut says there's probably a better alternative :/
9. `_throwTypeException` could return a better debuggable message, which you could return in the `Extra` argument of the Error. For example "Expected Object but received String".

**Comment by kczx3** [comment]
For what its worth, no one is being forced to use the underscore as a shorthand.  That's just what works for the author and is how the sample on the forum is shown.  But nothing about the library forces that at all from what I can see.

**Comment by Chunjee** [comment]
I will try to break this down into 10 different reports

\# 6 is done

**Comment by Chunjee** [comment]
I think concerning # 1 there is a bigger issue which is the only way to access the superglobal is to use the variable name `adash`

I can think of one way to solve this but I am not a fan of it

**Comment by Chunjee** [comment]
I was not able to fix # 9 as I do not know the better debuggable message

**Comment by Chunjee** [comment]
\# 2 and \# 3 were resolved

https://github.com/adash-ahk/adash.ahk/commit/c427698d7b484b3d581aff1361f17fe2a84cb031

**Comment by Descolada** [comment]
> I think concerning # 1 there is a bigger issue which is the only way to access the superglobal is to use the variable name `adash`

Wdym? If you reassign it in the global scope then you can use it as you would `adash` (there aren't "superglobals" in v2). Read-writing objects doesn't require declaring them as `global` in functions etc.

> I was not able to fix # 9 as I do not know the better debuggable message

What I meant was something like this:
```
        if (!isObject(param_array)) {
	        this._throwTypeException("Object", Type(param_array))
        }
	static _throwTypeException(expectedType, receivedType) {
		if (this.throwExceptions == true) {
			throw valueError("Type Error", -2, "Expected " expectedType " but received " receivedType)
		}
	}
```

**Comment by Chunjee** [comment]
Wonderful yes 👍
